//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R3MUS.Devpack.Recruitment.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("R3MUS.Devpack.Recruitment.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant.
        /// </summary>
        public static string ApplicantEndpointName {
            get {
                return ResourceManager.GetString("ApplicantEndpointName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no error..
        /// </summary>
        public static string NotAnError1 {
            get {
                return ResourceManager.GetString("NotAnError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Megadoubleplusgood. Everything is awesome. Please reboot universe &amp; try again..
        /// </summary>
        public static string NotAnError2 {
            get {
                return ResourceManager.GetString("NotAnError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m watching you through the window &amp; touching myself. Ooooooo, yeah..
        /// </summary>
        public static string NotAnError3 {
            get {
                return ResourceManager.GetString("NotAnError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monkey Trousers. That is all..
        /// </summary>
        public static string NotAnError4 {
            get {
                return ResourceManager.GetString("NotAnError4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Things that make you go &quot;Mmmm&quot;: Electro-Convulsive Therapy..
        /// </summary>
        public static string NotAnError5 {
            get {
                return ResourceManager.GetString("NotAnError5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Jungle. We got fun &amp; games (my favourite is Hungry Hippos)..
        /// </summary>
        public static string NotAnError6 {
            get {
                return ResourceManager.GetString("NotAnError6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel_Manager.
        /// </summary>
        public static string Personnel_Manager {
            get {
                return ResourceManager.GetString("Personnel_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screener.
        /// </summary>
        public static string ScreenerEndpointName {
            get {
                return ResourceManager.GetString("ScreenerEndpointName", resourceCulture);
            }
        }
    }
}
